# Generated by Django 2.2.10 on 2020-04-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trynumber',
        ),
        migrations.AddField(
            model_name='player',
            name='player_session',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='trynumber',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ManyToManyField(through='game.PlayerGameInfo', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
